name: Release

on: workflow_dispatch

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v4
      with:
        ref: main

    - name: Get next tag
      id: tag
      run: echo "NEXT_VERSION=`gh release list | grep "Draft" | awk '{print $3}'`" >> $GITHUB_OUTPUT

    - name: Get versions
      id: versions
      run: |
        echo "MAJOR=`echo ${{ steps.tag.outputs.NEXT_VERSION }} | sed -r "s/v([0-9]+)\.([0-9]+)\.([0-9]+).*/\1/"`" >> $GITHUB_OUTPUT
        echo "MINOR=`echo ${{ steps.tag.outputs.NEXT_VERSION }} | sed -r "s/v([0-9]+)\.([0-9]+)\.([0-9]+).*/\2/"`" >> $GITHUB_OUTPUT
        echo "PATCH=`echo ${{ steps.tag.outputs.NEXT_VERSION }} | sed -r "s/v([0-9]+)\.([0-9]+)\.([0-9]+).*/\3/"`" >> $GITHUB_OUTPUT

    - name: Set versions
      run: |
        sed -i -zr "s/set\(MPCXPARSER_VERSION_MAJOR [0-9]*\)/set(MPCXPARSER_VERSION_MAJOR ${{ steps.versions.outputs.MAJOR }})/" CMakeLists.txt
        sed -i -zr "s/set\(MPCXPARSER_VERSION_MINOR [0-9]*\)/set(MPCXPARSER_VERSION_MINOR ${{ steps.versions.outputs.MINOR }})/" CMakeLists.txt
        sed -i -zr "s/set\(MPCXPARSER_VERSION_PATCH [0-9]*\)/set(MPCXPARSER_VERSION_PATCH ${{ steps.versions.outputs.PATCH }})/" CMakeLists.txt
        sed -i -zr "s/GIT_TAG v([0-9]*).([0-9]*).([0-9]*)/GIT_TAG v${{ steps.versions.outputs.MAJOR }}.\2.\3/" README.md
        sed -i -zr "s/GIT_TAG v([0-9]*).([0-9]*).([0-9]*)/GIT_TAG v\1.${{ steps.versions.outputs.MINOR }}.\3/" README.md
        sed -i -zr "s/GIT_TAG v([0-9]*).([0-9]*).([0-9]*)/GIT_TAG v\1.\2.${{ steps.versions.outputs.PATCH }}/" README.md

    - name: Commit updates
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "action"
        git add .
        git commit -m "Update Versions by Github Actions"
        git branch -M release
        git push -u origin release

    - name: Create release PR
      run: |
        gh pr create                                                          \
          --title "Bump version number"                                       \
          --body "Auto-generater pull request to update the version number."  \
          --base main                                                         \
          --head release                                                      \
          --repo ${{ github.repository }}                                     \
          --label bot,skip-changelog
